const $ = selector => document.querySelector(selector);
let plan = null, state = null;
const statusText = { moved: '已移动', failed: '移动失败', skipped_changed: '已跳过：文件已变化', undone: '已撤销', undo_failed: '撤销失败' };

function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
function fileIcon(name) { const ext = name.split('.').pop().toLowerCase(); return ({ pdf:'PDF', docx:'DOC', doc:'DOC', xlsx:'XLS', xls:'XLS', pptx:'PPT', png:'IMG', jpg:'IMG', jpeg:'IMG', zip:'ZIP' }[ext] || 'FILE'); }
function renderPlan() {
  const items = plan?.items || []; const selected = items.filter(item => item.selected);
  const groups = window.PlanInteractions.groupPlanItems(plan);
  const unresolved = selected.filter(item => item.requiresChoice).length;
  $('#fileCount').textContent = selected.length; $('#folderCount').textContent = groups.length; $('#keepCount').textContent = items.length - selected.length;
  $('#scanNote').textContent = unresolved ? `${unresolved} 项需要先选择整理目标。` : (plan?.skipped?.length ? `${plan.skipped.length} 项因安全规则保留原位。` : '所有建议均可在确认前修改。');
  $('#applyBtn').disabled = (!selected.length && !(plan?.targets?.length)) || unresolved > 0; $('#intro').classList.toggle('scanned', !!plan);
  $('#resetBtn').hidden = !plan;
  if (!groups.length) { $('#canvas').innerHTML = '<div class="empty"><span>⌘</span><h3>没有可整理的文件</h3><p>桌面已很整洁，或所有项目都被安全规则跳过。</p></div>'; return; }
  $('#canvas').innerHTML = groups.map(({ targetDir: target, bucket, items: entries }) => `<article class="folder" data-target="${escapeHtml(target)}"><div class="folder-top"><div><span class="folder-icon">▰</span><span class="tag ${target.includes('待确认') ? 'warm' : ''}">${target.includes('待确认') ? '待确认' : '新建目标'}</span><h3>${escapeHtml(bucket)}</h3><p>${escapeHtml(target)}</p></div><button class="open" data-open="${escapeHtml(target)}">打开</button></div><div class="cards">${entries.length ? entries.map(item => `<div class="file-card" draggable="true" data-id="${item.id}"><span class="file-type">${fileIcon(item.name)}</span><div><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.reason)}</small>${item.requiresChoice ? `<select class="target-choice" data-choice-id="${item.id}"><option value="">选择整理目标…</option>${item.candidates.map((candidate, index) => `<option value="${index}">${escapeHtml(candidate.bucket)}（匹配“${candidate.keyword}”）</option>`).join('')}</select>` : ''}</div><button class="unselect" aria-label="本次不整理 ${escapeHtml(item.name)}" title="本次不整理" data-remove-id="${item.id}">×</button></div>`).join('') : '<p class="empty-folder">本次没有待整理文件</p>'}</div></article>`).join('');
  document.querySelectorAll('.unselect').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); if (window.PlanInteractions.removePlannedItem(plan, button.dataset.removeId)) renderPlan(); }));
  document.querySelectorAll('.target-choice').forEach(select => select.addEventListener('change', () => { const item = plan.items.find(candidate => candidate.id === select.dataset.choiceId); const target = item?.candidates?.[Number(select.value)]; if (!target) return; item.targetDir = target.targetDir; item.destinationPath = `${target.targetDir}\\${item.name}`; item.bucket = target.bucket; item.requiresChoice = false; item.reason = `已在预览中选择 → ${target.name}`; renderPlan(); }));
  document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', () => window.tidy.openPath(button.dataset.open)));
  document.querySelectorAll('.file-card').forEach(card => { card.addEventListener('dragstart', event => event.dataTransfer.setData('text/plain', card.dataset.id)); });
  document.querySelectorAll('.folder').forEach(folder => { folder.addEventListener('dragover', event => event.preventDefault()); folder.addEventListener('drop', event => { event.preventDefault(); const item = plan.items.find(x => x.id === event.dataTransfer.getData('text/plain')); if (!item) return; item.targetDir = folder.dataset.target; item.destinationPath = `${item.targetDir}\\${item.name}`; item.bucket = folder.querySelector('h3').textContent; item.reason = '已在预览中手动调整'; renderPlan(); }); });
}
function addRule(rule = { kind: 'project', name: '', keywords: [], priority: 0 }) { const node = $('#ruleTemplate').content.cloneNode(true); const row = node.querySelector('.rule'); row.querySelector('select').value = rule.kind || 'project'; row.querySelector('.rule-name').value = rule.name || ''; row.querySelector('.rule-keywords').value = (rule.keywords || []).join(', '); row.querySelector('.rule-priority').value = Number(rule.priority) || 0; row.querySelector('.delete').onclick = () => row.remove(); $('#rules').append(node); }
function collectRules() { return [...document.querySelectorAll('.rule')].map(row => ({ kind: row.querySelector('select').value, name: row.querySelector('.rule-name').value.trim(), keywords: window.KeywordParser.splitKeywords(row.querySelector('.rule-keywords').value), priority: Math.max(0, Number(row.querySelector('.rule-priority').value) || 0), enabled: true })).filter(rule => rule.name && rule.keywords.length); }
function showSettings() { $('#rootInput').value = state.archiveRoot; $('#rules').innerHTML = ''; state.rules.forEach(addRule); $('#settingsDialog').showModal(); }
function showHistory() { const history = state.history || []; $('#historyList').innerHTML = history.length ? history.map(batch => { const moved = batch.items.filter(i => i.status === 'moved').length; const undone = batch.items.filter(i => i.status === 'undone').length; return `<div class="history"><div><b>${new Date(batch.executedAt || batch.createdAt).toLocaleString('zh-CN')}</b><p>${moved} 项已整理${undone ? ` · ${undone} 项已撤销` : ''}</p></div><button class="ghost undo" data-batch="${batch.id}" ${moved ? '' : 'disabled'}>撤销本次</button></div>`; }).join('') : '<p class="hint">还没有整理记录。</p>'; $('#historyDialog').showModal(); document.querySelectorAll('.undo').forEach(button => button.onclick = async () => { try { const batch = await window.tidy.undo(button.dataset.batch); state.history = state.history.map(old => old.id === batch.id ? batch : old); showHistory(); $('#footerNote').textContent = '已完成撤销；如原位置有同名文件，相关项会保持原状。'; } catch (e) { alert(e.message); } }); }
async function init() { state = await window.tidy.state(); }
$('#scanBtn').onclick = async () => { try { plan = await window.tidy.scan(); renderPlan(); } catch (e) { alert(`无法扫描桌面：${e.message}`); } };
$('#resetBtn').onclick = () => { plan = window.PlanInteractions.resetPreview(plan); $('#footerNote').textContent = '已返回初始页；本次预览未执行，桌面文件没有任何变化。'; renderPlan(); };
$('#applyBtn').onclick = async () => { if (!confirm(`将移动 ${plan.items.filter(x => x.selected).length} 个文件。确认后仍可在历史中撤销。`)) return; try { const batch = await window.tidy.execute(plan); state.history.unshift(batch); const counts = batch.items.reduce((r, x) => (r[x.status] = (r[x.status] || 0) + 1, r), {}); $('#footerNote').textContent = `已完成：${counts.moved || 0} 项移动，${counts.failed || 0} 项失败，${counts.skipped_changed || 0} 项跳过。可在「整理历史」撤销。`; plan = null; renderPlan(); } catch (e) { alert(e.message); } };
$('#settingsBtn').onclick = showSettings; $('#historyBtn').onclick = showHistory; $('#addRule').onclick = () => addRule(); $('#chooseRoot').onclick = async () => { const selected = await window.tidy.chooseRoot(); if (selected) $('#rootInput').value = selected; };
$('#saveSettings').onclick = async event => { event.preventDefault(); try { state = await window.tidy.saveSettings({ archiveRoot: $('#rootInput').value.trim(), rules: collectRules() }); $('#settingsDialog').close(); plan = null; renderPlan(); } catch (e) { alert(e.message); } };
$('#newFolderBtn').onclick = async () => { try { if (!plan) plan = await window.tidy.scan(); $('#newTargetName').value = ''; $('#newTargetHint').textContent = `文件夹会创建在「${state.archiveRoot} / 进行中」；确认应用整理后才会写入磁盘。`; $('#newTargetDialog').showModal(); $('#newTargetName').focus(); } catch (error) { alert(`无法新建目标：${error.message}`); } };
$('#newTargetForm').onsubmit = event => { event.preventDefault(); const cleanName = $('#newTargetName').value.trim(); if (!window.PlanInteractions.isValidTargetName(cleanName)) { $('#newTargetHint').textContent = '文件夹名称不能为空，也不能包含 \\ / : * ? " < > |。'; return; } const target = `${state.archiveRoot}\\进行中\\${cleanName}`; if (!window.PlanInteractions.addPreviewTarget(plan, { targetDir: target, bucket: `进行中/${cleanName}` })) { $('#newTargetHint').textContent = '该目标已在当前预览中。'; return; } $('#newTargetDialog').close(); $('#footerNote').textContent = `已添加「${cleanName}」；可把文件拖到该目标，再应用整理。`; renderPlan(); };
$('#closeNewTarget').onclick = () => $('#newTargetDialog').close(); $('#cancelNewTarget').onclick = () => $('#newTargetDialog').close();
init();
